name: Train and publish model

on:
  schedule:
    - cron: '45 11 * * *'   # 18:45 VN = 11:45 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # DÙNG PYTHON 3.10 cho ổn định với TF 2.14
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (pin numpy 1.26.4)
        run: |
          python -m pip install --upgrade pip
          pip install "numpy==1.26.4"
          pip install --no-cache-dir "tensorflow-cpu==2.14.0"
          pip install --no-cache-dir requests beautifulsoup4

      - name: Show versions
        run: |
          python -c "import sys, numpy, tensorflow as tf; print(sys.version); print('numpy', numpy.__version__); print('tf', tf.__version__)"

      - name: Train & export
        run: python train_model.py

      - name: Commit model & version.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add model.tflite version.json
          git commit -m "auto: update model" || echo "Nothing to commit"
          git push
