name: Train and publish model

on:
  schedule:
    - cron: '45 11 * * *'   # 18:45 VN (UTC+7) = 11:45 UTC
  workflow_dispatch: {}     # cho phép Run workflow thủ công

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow-cpu==2.14.0 beautifulsoup4 requests

      - name: Train & export
        run: python train_model.py

      - name: Commit model & version.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add model.tflite version.json
          git commit -m "auto: update model" || echo "Nothing to commit"
          git push
